import type { Metadata } from "next"
import FooterSection from "@/components/footer"

export const metadata: Metadata = {
  title: "Tailark Quartz pages",
  description: "Generated by create next app",
}

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <main role="main" className="bg-background">
        {children}
      </main>
      {/* <FooterSection /> */}
    </>
  )
}
