import type { Metadata } from 'next'
import Header from '@/app/grid-2/components/header'
import FooterSection from '@/app/grid-2/components/footer'

export const metadata: Metadata = {
    title: 'Tailark Quartz pages',
    description: 'Generated by create next app',
}

export default function MarketingLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <>
            <Header />
            <main
                role="main"
                className="bg-zinc-950/10">
                {children}
            </main>
            <FooterSection />
        </>
    )
}